//
//  CountriesList.swift
//  Yoose
//
//  Created by Indigo´sDad on 2020-03-08.
//  Copyright © 2020 Indigo´sDad. All rights reserved.
//

import Foundation

struct Countries {
    
    var countries = [ "Andorra",
                 "United Arab Emirates",
                 "Afghanistan",
                 "Antigua and Barbuda",
                 "Anguilla",
                "Albania",
                "Armenia",
                 "Angola",
                "Antarctica",
                "Argentina",
                "American Samoa",
               "Austria",
                "Australia",
                "Aruba",
                "Åland Islands",
                "Azerbaijan",
                "Bosnia and Herzegovina",
                "Barbados",
                "Bangladesh",
              "Belgium",
                 "Burkina Faso",
               "Bulgaria",
               "Bahrain",
               "Burundi",
                "Benin",
               "Saint Barthélemy",
                "Bermuda",
                 "Brunei Darussalam",
                "Bolivia, Plurinational State of",
                 "Bonaire, Sint Eustatius and Saba",
                "Brazil",
               "Bahamas",
                 "Bhutan",
               "Bouvet Island",
                "Botswana",
               "Belarus",
                 "Belize",
              "Canada",
                "Cocos (Keeling) Islands",
             "Congo, the Democratic Republic of",
                "Central African Republic",
               "Congo",
                "Switzerland",
               "Côte d'Ivoire",
                "Cook Islands",
                "Chile",
                "Cameroon",
                "China",
               "Colombia",
                "Costa Rica",
              "Cuba",
               "Cabo Verde",
              "Curaçao",
               "Christmas Island",
               "Cyprus",
                "Czech Republic",
    //D
                "Germany",
             "Djibouti",
               "Denmark",
                "Dominica",
                "Dominican Republic",
               "Algeria",
    //E
               "Ecuador",
                "Estonia",
                "Egypt",
                "Western Sahara",
                "Eritrea",
                "Spain",
               "Ethiopia",
    //F
               "Finland",
                "Fiji",
                "Falkland Islands (Malvinas)",
                "Micronesia, Federated States of",
                "Faroe Islands",
                "France",
    //G
             "Gabon",
              "United Kingdom of Great Britain and Northern Ireland",
             "Grenada",
             "Georgia",
              "French Guiana",
              "Guernsey",
                "Ghana",
                "Gibraltar",
                "Greenland",
                "Gambia",
               "Guinea",
                "Guadeloupe",
               "Equatorial Guinea",
                "Greece",
                "South Georgia and the South Sandwich Islands",
                "Guatemala",
                "Guam",
               "Guinea-Bissau",
              "Guyana",
    //H
           "Hong Kong",
               "Heard Island and McDonalds Islands",
             "Honduras",
               "Croatia",
               "Haiti",
                "Hungary",
    //I
             "Indonesia",
                "Ireland",
               "Israel",
              "Isle of Man",
                "India",
                "British Indian Ocean Territory",
               "Iraq",
               "Iran, Islamic Republic of",
                "Iceland",
              "Italy",
    //J
               "Jersey",
               "Jamaica",
               "Jordan",
               "Japan",
    //K
               "Kenya",
                "Kyrgyzstan",
             "Cambodia",
                "Kiribati",
              "Comoros",
                "Saint Kitts and Nevis",
                "Korea, Democratic People's Republic of",
                "Korea, Republic of",
                "Kuwait",
               "Cayman Islands",
                "Kazakhstan",
    //L
                "Lao People's Democratic Republic",
              "Lebanon",
                "Saint Lucia",
                "Liechtenstein",
                "Sri Lanka",
                "Liberia",
                "Lesotho",
                "Lithuania",
                "Luxembourg",
                "Latvia",
    //M
               "Morocco",
              "Monaco",
                "Moldova, Republic of",
                "Montenegro",
               "Saint Martin (French part)",
               "Madagascar",
               "Marshall Islands",
                "Macedonia, the former Yugoslav Republic of",
                "Mali",
               "Myanmar",
                "Mongolia",
                "Macao","Northern Mariana Islands",
                "Martinique",
               "Mauritania",
                "Montserrat",
                "Malta",
                "Mauritius",
                "Maldives",
                "Malawi",
                "Mexico",
"Malaysia",
                "Mozambique",
    //N
              "Namibia",
                "New Caledonia",
                "Niger",
                "Norfolk Island",
                "Nigeria",
                "Nicaragua",
               "Netherlands",
                "Norway",
               "Nepal",
                "Nauru",
               "Niue",
                "New Zealand",
    //O
               "Oman",
    //P
               "Panama",
                "Peru",
             "French Polynesia",
               "Papua New Guinea",
                "Philippines",
                "Pakistan",
                "Poland",
                "Saint Pierre and Miquelon",
               "Pitcairn",
               "Puerto Rico",
                "Palestine, State of",
                "Portugal",
                "Palau",
                "Paraguay"
    //Q
               ,"Qatar",
    //R
                "Réunion",
                "Romania",
                "Serbia",
                "Russian Federation",
                "Rwanda",
    //S
               "Saudi Arabia",
                "Solomon Islands",
              "Seychelles",
                "Sudan",
                "Sweden",
                "Singapore",
                "Saint Helena, Ascension and Tristan da Cunha",
                "Slovenia",
               "Svalbard and Jan Mayen",
                "Slovakia",
               "Sierra Leone",
                "San Marino",
                "Senegal",
                "Somalia",
                "Suriname",
                "South Sudan",
                "Sao Tome and Principe",
                "El Salvador",
               "Sint Maarten (Dutch part)",
               "Syrian Arab Republic",
                "Swaziland",
    //T
                "Turks and Caicos Islands",
                "Chad",
                "French Southern Territories",
                "Togo",
                "Thailand",
               "Tajikistan",
                "Tokelau",
                "Timor-Leste",
               "Turkmenistan",
               "Tunisia",
                "Tonga",
               "Turkey",
                "Tuvalu",
                "Taiwan, Province of China",
               "Tanzania, United Republic of",
    //U
            "Ukraine",
                "Uganda",
                "United States Minor Outlying Islands",
               "United States of America",
                "Uruguay",
                "Uzbekistan",
    //V
              "Holy See",
              "Saint Vincent and the Grenadines",
              "Venezuela, Bolivarian Republic of",
            "Virgin Islands, British",
                "Virgin Islands, U.S.",
               "Viet Nam",
                "Vanuatu",
    //W
              "Wallis and Futuna",
               "Samoa",
    //Y
              "Yemen",
              "Mayotte",
    //Z
              "South Africa",
                "Zambia",
                "Zimbabwe"]
}
